# Generated by Django 3.2.16 on 2025-02-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_comment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='current_post',
            new_name='post_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
