# Generated by Django 3.2.16 on 2025-02-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20250215_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='current_post',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
    ]
