# Generated by Django 3.2.16 on 2025-02-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comments_current_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='current_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
    ]
